### ISSUE TITLE
Not working on Mac OS 10.10

### ISSUE THREAD

**Issue by areichert** [dcarroll/sublime-lightning#18]
Hi, I am trying to run the plugin on Mac OS 10.10, MavensMate 0.0.2, ForceCLI. I added ForceCLI to my $Path varible, running smoothly on terminal. But when I try to install the lightning plugin I'll reveive the following Error:
Sublime Lightning Plugin requires the Force.com CLI to function

Please visit force-cli.herokuapp.com to installthe Force.com CLI.

If you have already installed it, please make sure that you have stored it or created a symlink to it in Sublime's default path.

I found a hint on http://salesforce.stackexchange.com/questions/83457/trouble-making-cli-command-line-interface-work-with-sublime-on-mac-os-x, but this plugin seems not working too.

MavensMate itself runs like charm - I have no Idea what the problem could be.
Do you have any hint for me what "Sublime's default path" is?

**Comment by dcarroll** [comment]
Create a symlink to the force cli executable in the /usr/local/bin folder.
Sublime doesn't really pay attention to /usr/bin or you path variable.



On Tue, Sep 22, 2015 at 1:07 PM, areichert <notifications@github.com> wrote:

> Hi, I am trying to run the plugin on Mac OS 10.10, MavensMate 0.0.2,
> ForceCLI. I added ForceCLI to my $Path varible, running smoothly on
> terminal. But when I try to install the lightning plugin I'll reveive the
> following Error:
> Sublime Lightning Plugin requires the Force.com CLI to function
>
> Please visit force-cli.herokuapp.com to installthe Force.com CLI.
>
> If you have already installed it, please make sure that you have stored it
> or created a symlink to it in Sublime's default path.
>
> I found a hint on
> http://salesforce.stackexchange.com/questions/83457/trouble-making-cli-command-line-interface-work-with-sublime-on-mac-os-x,
> but this plugin seems not working too.
>
> MavensMate itself runs like charm - I have no Idea what the problem could
> be.
> Do you have any hint for me what "Sublime's default path" is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/18>.
>



-- 
Thanks,
Dave

**Comment by areichert** [comment]
Well, this is exactly what I did. As I mentioned before - I could run force from every folder in terminal so the simlink works as it is:
![bildschirmfoto 2015-09-23 um 08 06 13](https://cloud.githubusercontent.com/assets/1327030/10038768/9178bb0e-61ca-11e5-99d9-9ec0bf47ae4a.png)
.

**Comment by dcarroll** [comment]
Is there a symlink also in /usr/bin?

On Tue, Sep 22, 2015 at 11:11 PM, areichert <notifications@github.com>
wrote:

> Well, this is exactly what I did. As I mentioned before - I could run
> force from every folder in terminal so the simlink works as it is:
> [image: bildschirmfoto 2015-09-23 um 08 06 13]
> <https://cloud.githubusercontent.com/assets/1327030/10038768/9178bb0e-61ca-11e5-99d9-9ec0bf47ae4a.png>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/18#issuecomment-142505004>
> .
>



-- 
Thanks,
Dave

**Comment by tscottdev** [comment]
Hi ariechert, 

I got this working with a bit of messing around ...

The Sublime Path plugin doesn't  work for me either, could be that El Capitan is the issue here.

Workaround is this:

1. Create a symbolic link to sublime in /usr/local/bin (as this should be on your path). Open Terminal and use the command:

sudo ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

2. Now create a symbolic link to Dave's force plugin:

sudo ln -s __/replace_with_your_path__/force /usr/local/bin/force

3. Open Terminal and run:

subl

Good luck, Tony

**Comment by monishstrithick** [comment]
I am still getting this error.

**Comment by jettdigital** [comment]
I had the same issue, it was working then I upgraded to El Capitan and it stopped working. @tscottdev solution worked for me.

1. Create a symlink to the Force CLI in /usr/local/bin
2. Create a symlink to Sublime Text in /usr/local/bin
2. Open a terminal and start Sublime from the command line using the /usr/local/bin symlink

**Comment by Jeremywhiteley** [comment]
For those using a Mac, go to https://force-cli.heroku.com and download the Mac version. All you get in your Downloads folder is a single file called "force". There is no installer, you just have to put this file someplace that makes sense. I moved it to a place where my path could see it and made sure it was executable for me.

mv ~/Downloads/force /usr/local/bin  
chmod u+x /usr/local/bin/force  
sudo ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

Then type in subl and it should work.

**Comment by Cristobal69** [comment]
Just followed all the process and by trying to fetch lightning components: 

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2e19a]

goroutine 1 [running]:
main.(*Force).Query(0x0, 0x820839130, 0x4b, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/app/work/src/src/github.com/heroku/force/force.go:674 +0x91a
main.runQuery(0x78f6c0, 0x820838110, 0x1, 0x3)
	/app/work/src/src/github.com/heroku/force/query.go:49 +0x31d
main.main()
	/app/work/src/src/github.com/heroku/force/main.go:55 +0x2f2

goroutine 5 [syscall]:
os/signal.loop()
	/app/vendor/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/app/vendor/go/src/os/signal/signal_unix.go:28 +0x37

An idea?

**Comment by dcarroll** [comment]
I'll take a look.  Can you tell me what version of the CLI you are using?

`force version`

**Comment by Cristobal69** [comment]
The last one, just downloaded yesterday from https://force-cli.heroku.com/

**Comment by jonathanconway** [comment]
This issue appears to be more easily fixed by installing a Sublime Package called [Fix Mac Path](https://github.com/int3h/SublimeFixMacPath). (See [Trouble making CLI (Command Line Interface) work with sublime on MAC OS X](http://salesforce.stackexchange.com/questions/83457/trouble-making-cli-command-line-interface-work-with-sublime-on-mac-os-x)).

**Comment by alderete-sfdc** [comment]
FWIW, although I also receive the "Sublime Lightning Plugin requires the Force.com CLI to function" error message when I start up SublimeText, I'm actually able to use the plugin's functionality just fine.

Mac OS X 10.10.5
Force CLI installed in /usr/local/bin (downloaded and installed today)
SublimeText 3 (latest Stable channel, build 3103)
Sublime subl symlink in ~/bin
Fix Mac Path plugin installed

I received the error both before and after installing the Fix Mac Path plugin. I failed to test Sublime Lightning before installing it, so I can't say if the Fix Mac Path plugin had an effect.

**Comment by sayeeda** [comment]
Same Problem am also facing please help me
