### ISSUE TITLE
Unable to fetch Lightning components using Force CLI (using directly or via sublime plugin)

### ISSUE THREAD

**Issue by donmac23** [dcarroll/sublime-lightning#29]
I am using Windows 64 bit v0.22.50 of force CLI on Windows 7.
After successfully logging in, I run the following command:
`force fetch -t Aura -n InventoryList -d "C:\Users\chdmcint
\workspace\lightning"
`
Here is the response:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x42b982]

goroutine 1 [running]:
main.(*Force).GetAuraBundleByName(0x0, 0xc082002310, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/heroku/force/force.go:499 +0x592
main.(*Force).GetAuraBundle(0x0, 0xc082002310, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/heroku/force/force.go:487 +0xb3
main.runFetchAura2(0xba1e80, 0xc082002310, 0xd)
        /home/travis/gopath/src/github.com/heroku/force/fetch.go:89 +0x164
main.runFetch(0xba1e80, 0xc082056070, 0x0, 0x0)
        /home/travis/gopath/src/github.com/heroku/force/fetch.go:200 +0x1aa
main.main()
        /home/travis/gopath/src/github.com/heroku/force/main.go:55 +0x2f9
`
I get same result if I try fetching lightning components from Sublime.

**Comment by dcarroll** [comment]
Sorry you are having this issue. I'll try to find the reason, but may take
a day or two.

Dave Carroll

On Feb 24, 2016, at 2:38 PM, donmac23 <notifications@github.com> wrote:

I am using Windows 64 bit v0.22.50 of force CLI on Windows 7.
After successfully logging in, I run the following command:
force fetch -t Aura -n InventoryList -d "C:\Users\chdmcint
\workspace\lightning"

Here is the response:
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x0 pc=0x42b982]

goroutine 1 [running]:
main.(

*Force).GetAuraBundleByName(0x0, 0xc082002310, 0xd, 0x0, 0x0, 0x0, 0x0,
0x0, 0x0, 0x0, ...)
/home/travis/gopath/src/github.com/heroku/force/force.go:499
<http://github.com/heroku/force/force.go:499> +0x592
main.(*Force).GetAuraBundle(0x0,
0xc082002310, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/home/travis/gopath/src/github.com/heroku/force/force.go:487 +0xb3
main.runFetchAura2(0xba1e80, 0xc082002310, 0xd)
/home/travis/gopath/src/github.com/heroku/force/fetch.go:89 +0x164
main.runFetch(0xba1e80, 0xc082056070, 0x0, 0x0)
/home/travis/gopath/src/github.com/heroku/force/fetch.go:200 +0x1aa
main.main()
/home/travis/gopath/src/github.com/heroku/force/main.go:55 +0x2f9
`
I get same result if I try fetching lightning components from Sublime.

—
Reply to this email directly or view it on GitHub
<https://github.com/dcarroll/sublime-lightning/issues/29>.

**Comment by donmac23** [comment]
Perhaps a firewall issue? I notice that even if I just run force whoami, I get a similar result.

**Comment by dcarroll** [comment]
Ah, that is helpful. Are you behind a firewall?

Dave Carroll

On Feb 24, 2016, at 2:54 PM, donmac23 <notifications@github.com> wrote:

Perhaps a firewall issue? I notice that even if I just run force whoami, I
get a similar result.

—
Reply to this email directly or view it on GitHub
<https://github.com/dcarroll/sublime-lightning/issues/29#issuecomment-188496930>
.

**Comment by donmac23** [comment]
Yes. I will try from outside the work network later and let you know how
that goes.

**Comment by BigKie1** [comment]
I have exactly the same issue with both version 22.28 and 22.52 of Force CLI. Just tried force whoami which also failed. Other people on my network are using this without issue. It was originally happening on Mavericks and still on El Captain.

**Comment by mkparthipan** [comment]
Hi Ben,
 I had same issue while i was trying to use  from sublime.  I assumed that login through mavesmate will work. But in sublime i have explicitly login using CLI. Once i logged in, everything started working fine.
Later whoami  from terminal also worked.  If you are using sublime, open any project using mavenmate. Then right click on the project. click lightning. click salesforce login. enter credentials. Then everything should work  fine.

**Comment by michaelwit1** [comment]
Dave

I am getting the above issue today, for no apparent reason, after using the lightning plugin successfully for several weeks.  Has something suddenly changed?

(No issue running force login or force whoami)

**Comment by michaelwit1** [comment]
Error output:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x45f37c]

goroutine 1 [running]:
main.InAuraBundlesFolder(0xc082122180, 0x75, 0x0)
	/home/travis/gopath/src/github.com/heroku/force/pushAura.go:289 +0x5c
main.runPushAura(0xba1a20, 0xc0820db2e0, 0x1, 0x1)
	/home/travis/gopath/src/github.com/heroku/force/pushAura.go:39 +0x21f
main.runAura(0xba1a20, 0xc082006160, 0x3, 0x3)
	/home/travis/gopath/src/github.com/heroku/force/aura.go:111 +0x683
main.main()
	/home/travis/gopath/src/github.com/heroku/force/main.go:55 +0x2f9
[Finished in 0.2s with exit code 2]
[cmd: ['force', 'aura', 'push', '-f', "'C:\\maven\\workspace\\NOJV\\metadata\\aura\\AccountList\\AccountList.cmp'"]]
[dir: C:\maven\workspace\NOJV\metadata\aura\AccountList]
[path: C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;c:\mars]

**Comment by michaelwit1** [comment]
Clarification:  Unlike the previous posts, I can successfully fetch the lightning components into metadata, however when I attempt to save any component I get the above error.

**Comment by dcarroll** [comment]
Ok, will take a look in about an hour or so (meetings...)

**Comment by dcarroll** [comment]
Michael, are you using the latest version of the CLI and the Sublime Plugin?

On Mon, May 9, 2016 at 1:28 AM, michaelwit1 <notifications@github.com>
wrote:

> Clarification: Unlike the previous posts, I can successfully fetch the
> lightning components into metadata, however when I attempt to save any
> component I get the above error.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/dcarroll/sublime-lightning/issues/29#issuecomment-217805271>
>



-- 
Thanks,
Dave

**Comment by michaelwit1** [comment]
Many thanks, Dave - upgrading to the latest CLI (v0.22.57) fixed the problem.  (I had v0.22.52)

**Comment by shutchup** [comment]
Hi Dave,

The plugin was working fine till now. Suddenly from morning it has started throwing the same error which many have discussed here -

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x45f82c]

goroutine 1 [running]:
main.InAuraBundlesFolder(0xc0820677c0, 0x98, 0x0)
    /home/travis/gopath/src/github.com/heroku/force/pushAura.go:289 +0x5c
main.runPushAura(0xba2ae0, 0xc0820d74b0, 0x1, 0x1)
    /home/travis/gopath/src/github.com/heroku/force/pushAura.go:39 +0x21f
main.runAura(0xba2ae0, 0xc08200a1b0, 0x3, 0x3)
    /home/travis/gopath/src/github.com/heroku/force/aura.go:111 +0x683
main.main()
    /home/travis/gopath/src/github.com/heroku/force/main.go:56 +0x2f9
[Finished in 0.1s with exit code 2]
[cmd: ['force', 'aura', 'push', '-f', 

Can you please help ?

**Comment by shutchup** [comment]
Sorry my bad -

force update command did not show any updates for CLI so I thought my CLI was up-to-date but that was not the case.

Just manually downloaded the CLI from the heroku portal again and replaced the older version of it's executable.

Verified the new version to be v0.22.57 using [force version] command.

And it worked just like before !!!

Thank you all for your help

**Comment by edelrabe** [comment]
I had the same error today. I installed force cli to use it with Sublime lightning plugin. First I logged in from Sublime and then I got this error when tried to fetch metadata.
Then I logged in using force cli and the error gone. Maybe it's lightning plugin issue...

**Comment by dcarroll** [comment]
Sorry for the poor timing, I am on holiday in Costa Rica without my laptop.
I will fix this issue on Friday when I'm back.

Sent from my iPhone

On Jun 14, 2016, at 11:27 AM, Salavat Ianberdin <notifications@github.com>
wrote:

I had the same error today. I installed force cli to use it with Sublime
lightning plugin. First I logged in from Sublime and then I got this error
when tried to fetch metadata.
Then I logged in using force cli and the error gone. Maybe it's lightning
plugin issue...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dcarroll/sublime-lightning/issues/29#issuecomment-225954577>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAHGHhDOYKzL3UvxMQVrZNmzr1p3y_S_ks5qLuR6gaJpZM4HiMuJ>
.

**Comment by abuffa** [comment]
Hi, 

Any updates about this issue? I'm experiencing the same problem. I updated the plugin, but I'm still unable to save changes. 

Thanks!

**Comment by dcarroll** [comment]
Please install the latest version of the Force CLI.

Sent from my iPhone

On Jun 24, 2016, at 7:30 AM, Angelica <notifications@github.com> wrote:

Hi,

Any updates about this issue? I'm experiencing the same problem. I updated
the plugin, but I'm still unable to save changes.

Thanks!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/dcarroll/sublime-lightning/issues/29#issuecomment-228361419>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAHGHohrsZgWKHIrp5tW8LSrKCbWj1cZks5qO-n8gaJpZM4HiMuJ>
.
